### PR TITLE
Add option to not generate blood trails for hidden tokens

### PR DESCRIPTION
**Pull request by kimitsu**
When the GM hides tokens from the view of players, they still continue to generate blood trails, thus giving away the token position and movement. The GM may have other reasons for hiding tokens beside utilizing some sort of stealth mechanics, for example removing them from the view of the scene without actually losing access to the tokens for convenience. Having them still produce blood visible to other players may be detrimental. This fix provides an option (which is supposed to be a default, in my opinion), to not generate blood trails for hidden tokens.

### CODE REVIEW

**Comment by theripper93** [comment]
I will reconsider if this was actually an issue. If it was more people would have requested it , I’m not adding a setting for every little thing.

**Comment by kimitsu** [comment]
Sounds reasonable. Would you reconsider if it wouldn't be a setting but rather the default behavior? If you are explicitly against adding an associated setting.

**Comment by theripper93** [comment]
I don’t want it as default. I think having hidden token bleed is fine, it adds to the stealth mechanic, if more people feel it not fine I’m sure they will let me know and I will then reconsider

**Comment by kimitsu** [comment]
> I don’t want it as default. I think having hidden token bleed is fine, it adds to the stealth mechanic, if more people feel it not fine I’m sure they will let me know and I will then reconsider

Well this does sound like your personal preference to be honest. And contrary to system-agnostycism. Some systems don't even have stealth, and core hidden tokens are what they are - tokens that should not be seen by players. DM may always generate splatter with the button click if they want to "add" some mood to the stealthing monters if they need to, but the reverse is possible only by fiddling with blood transparency for each individual token? You can't be serious...

**Pull request closed without merging**
